name: ConditionalPerms
author: Luck
version: ${project.version}
main: me.lucko.conditionalperms.ConditionalPerms
softdepend: [WorldGuard, Factions, CombatTagPlus, PlotSquared, PlaceholderAPI, Towny, VanishNoPacket]
description: Define permissions that only apply when conditions are met
commands:
  cperms:
    usage: /cperms
    description: Main command
permissions:
  conditionalperms.reload:
    description: Permission to reload all online users
    default: op
  conditionalperms.debug:
    description: Permission to toggle debug mode
    default: op